name: Build iOS Premium

on:
  workflow_dispatch: # Nos permite lanzar la compilación a mano cuando queramos
  push:
    branches: [ "main" ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: 📥 Clonar el código
        uses: actions/checkout@v3

      - name: 🐦 Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 Instalar dependencias de Flutter
        run: flutter pub get

      - name: 🍎 Instalar dependencias de Apple (CocoaPods)
        run: pod install
        working-directory: ios

      - name: 🚀 Compilar iOS (Unsigned)
        run: flutter build ios --release --no-codesign

      - name: 🎁 Empaquetar a formato .ipa
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r CroketaChat_Premium.ipa Payload

      - name: ☁️ Subir la App para descargar
        uses: actions/upload-artifact@v3
        with:
          name: CroketaChat-iOS-App
          path: CroketaChat_Premium.ipa
